import { describe, expect, it } from 'vitest';
import { getVariantLabel, hasBlocking } from '../variant-picker.utils';

describe('variant picker utils', () => {
  it('stable labels are generated by index', () => {
    expect(getVariantLabel(0)).toBe('Version A');
    expect(getVariantLabel(1)).toBe('Version B');
  });
  it('blocking detection works', () => {
    expect(hasBlocking({ id: 'x', site: { siteMap: { pages: [] } } as never, quality: { ok: false, issues: [], blockingCount: 1, warningCount: 0, infoCount: 0 } })).toBe(true);
  });
});
