import type { BusinessInput } from './business.types';
export const businessSampleData: Record<string, BusinessInput> = {
  minimalBusinessLanding: { productType: 'business_landing', scope: 'one_page', stylePresetId: 'minimal', data: { brandName: 'Northstar Consulting', tagline: 'Clarity that converts', services: [{ id: 's1', name: 'Strategy Session' }], offer: { primaryCta: 'Book a call' }, contact: { email: 'hello@northstar.co' } } },
  richBusinessLanding: { productType: 'business_landing', scope: 'one_page', stylePresetId: 'modern', data: { brandName: 'ScaleForge', tagline: 'Build repeatable growth', services: [{ id: 's1', name: 'Go-to-market' }, { id: 's2', name: 'CRO' }, { id: 's3', name: 'Automation' }, { id: 's4', name: 'Analytics' }], pricingPlans: [{ id: 'p1', name: 'Starter', price: '$499', features: ['1 channel'] }, { id: 'p2', name: 'Growth', price: '$1499', features: ['3 channels'] }, { id: 'p3', name: 'Scale', price: '$2999', features: ['all channels'] }], testimonials: [{ id: 't1', quote: 'Great ROI' }, { id: 't2', quote: 'Fast execution' }, { id: 't3', quote: 'Excellent team' }], faqs: [{ id: 'f1', question: 'How fast?', answer: '2 weeks' }, { id: 'f2', question: 'Contract?', answer: 'Monthly' }, { id: 'f3', question: 'Support?', answer: 'Included' }, { id: 'f4', question: 'Industry?', answer: 'B2B' }, { id: 'f5', question: 'Onboarding?', answer: 'Yes' }], contact: { email: 'team@scaleforge.com', phone: '+1 555 222', address: 'NYC', bookingUrl: 'https://cal.com/scaleforge' }, assets: { heroImageUrl: 'https://images.example.com/hero.jpg' } } },
  noImageBusiness: { productType: 'business_landing', scope: 'one_page', stylePresetId: 'minimal', data: { brandName: 'TextFirst Studio', services: [{ id: 's1', name: 'Brand Messaging' }] } },
  serviceHeavyBusiness: { productType: 'business_landing', scope: 'one_page', stylePresetId: 'tech', data: { brandName: 'OpsStack', services: Array.from({ length: 12 }).map((_, i) => ({ id: `s${i}`, name: `Service ${i}` })) } },
  noPricingBusiness: { productType: 'business_website', scope: 'mini_site_3_pages', stylePresetId: 'warm', data: { brandName: 'LocalCare', services: [{ id: 's1', name: 'Home Service' }], testimonials: [{ id: 't1', quote: 'Trusted local team' }] } },
  standardBusinessWebsite: { productType: 'business_website', scope: 'standard_site_5_pages', stylePresetId: 'modern', data: { brandName: 'Atlas Advisory', services: [{ id: 's1', name: 'Consulting' }, { id: 's2', name: 'Implementation' }], pricingPlans: [{ id: 'p1', name: 'Core', price: '$1200', features: ['Audit'] }] } }
};
