export * from './business.types';
export * from './business.sample-data';
export * from './business.site-recipe';
export * from './business.page-recipes';
export * from './business.blocks';
export * from './business.block-variants';
export * from './business.style-presets';
export * from './business.compatibility-rules';
export * from './business.validators';
export * from './business.fixtures';
export * from './business.registry';
export const businessPack = { id: 'business-pack-2', name: 'Business Landing/Site Pack' } as const;
