import type { WeddingInput } from './wedding.types';
const gallery8 = Array.from({ length: 8 }).map((_, i) => ({ id: `g${i}`, src: `https://img.example.com/w${i}.jpg`, alt: `Gallery ${i}` }));
const story4 = Array.from({ length: 4 }).map((_, i) => ({ id: `s${i}`, title: `Story ${i}`, description: `Milestone ${i}` }));
const schedule5 = Array.from({ length: 5 }).map((_, i) => ({ id: `sc${i}`, title: `Event ${i}`, time: `1${i}:00` }));
export const weddingSampleData: Record<string, WeddingInput> = {
  minimalWedding: { productType:'wedding_invitation', scope:'one_page', stylePresetId:'minimal', data:{ couple:{brideName:'Anna',groomName:'Ben'}, event:{date:'2026-11-18',venueName:'Rose Hall'}, rsvp:{enabled:false} } },
  richWedding: { productType:'wedding_invitation', scope:'one_page', stylePresetId:'luxury', data:{ couple:{brideName:'Linh',groomName:'Minh',displayNames:'Linh & Minh'}, event:{date:'2026-12-20',time:'17:00',venueName:'Grand Palace',venueAddress:'123 Love St',mapUrl:'https://maps.example.com/wed'}, message:{headline:'Together with families'}, story:{title:'Our Story',items:story4}, schedule:schedule5, gallery:gallery8, rsvp:{enabled:true,formAction:'https://forms.example.com/rsvp',contactEmail:'rsvp@example.com'}, gift:{enabled:true,message:'Your presence is our gift'}, music:{enabled:true,title:'Our Song',src:'https://cdn.example.com/song.mp3'}, assets:{heroImageUrl:'https://img.example.com/hero.jpg',coupleImageUrl:'https://img.example.com/couple.jpg'} } },
  noImageWedding: { productType:'wedding_invitation', scope:'one_page', stylePresetId:'classic', data:{ couple:{brideName:'Mai',groomName:'Nam'}, event:{date:'2026-08-08',venueName:'Lotus Garden'}, rsvp:{enabled:true,contactPhone:'+1 555 1010'} } },
  rsvpContactOnlyWedding: { productType:'wedding_invitation', scope:'mini_site_3_pages', stylePresetId:'warm', data:{ couple:{brideName:'Jade',groomName:'Kai'}, event:{date:'2026-09-01',venueName:'Moonlight Venue',venueAddress:'8 Sunset Blvd'}, rsvp:{enabled:true,contactEmail:'hello@wed.com',contactPhone:'+1 555 3300'} } },
  noMapWedding: { productType:'wedding_invitation', scope:'mini_site_3_pages', stylePresetId:'natural', data:{ couple:{brideName:'A',groomName:'B'}, event:{date:'2026-10-10',venueName:'Lake House',venueAddress:'44 Lake Rd'}, rsvp:{enabled:false} } },
  standardWeddingSite: { productType:'wedding_invitation', scope:'standard_site_5_pages', stylePresetId:'editorial', data:{ couple:{brideName:'Chris',groomName:'Drew'}, event:{date:'2026-07-14',venueName:'River Club',venueAddress:'7 River Dr'}, rsvp:{enabled:true,formAction:'https://forms.example.com/cd'} } }
};
